package com.example.daos;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORDER_ITEM".
 */
public class OrderItem {

    private Integer Num;
    private Float Price;
    private long orderid;

    public OrderItem() {
    }

    public OrderItem(Integer Num, Float Price, long orderid) {
        this.Num = Num;
        this.Price = Price;
        this.orderid = orderid;
    }

    public Integer getNum() {
        return Num;
    }

    public void setNum(Integer Num) {
        this.Num = Num;
    }

    public Float getPrice() {
        return Price;
    }

    public void setPrice(Float Price) {
        this.Price = Price;
    }

    public long getOrderid() {
        return orderid;
    }

    public void setOrderid(long orderid) {
        this.orderid = orderid;
    }

}
